version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: smart_clinic_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: smart_clinic_db
      MYSQL_USER: clinic_user
      MYSQL_PASSWORD: clinic_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - clinic_network

  app:
    build: .
    container_name: smart_clinic_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/smart_clinic_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql
    networks:
      - clinic_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  clinic_network:
    driver: bridge