server:
  port: 8080

spring:
  application:
    name: smart-clinic-management
  datasource:
    url: jdbc:mysql://localhost:3306/smart_clinic_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: smartClinicSecretKeyForJWTTokenGenerationThatShouldBeLongEnough
  expiration: 86400000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE